Getting And Cleaning Data Project
=============================

### Overview
This document describes the workings of a script (run_analysis.R) that transforms 
the input Samsung dataset to a tidy version containing mean values for a set of 
features. These means are calculated on a subject-activity pair basis. The features 
of which these means are calculated were selected from the input data by looking 
for "mean" and "std" in the feature labels of the original dataset. The output 
dataset is "complete" in the sense that it is a combination of the training and 
test data.

### Helper Functions
This script relies heavily on the use of helper functions. These are used to 
enhance readability.

### Installation of necessary packages
This script is reliant on the dplyr package. This package will be installed 
automatically if necessary.

### Input dataset
The project text states that the script shoul run as long as the input dataset 
is present in the same folder as the run_analysis.R script. If this dataset 
(the .zip file) is not present, the script will download it automatically and 
unzip it. This unziping operation will overwrite any prexisting folder structure 
with the same name. 

### Output dataset
The output dataset - named "tidyData.txt" - will be placed in the output folder. 
This file can be read into R by using the following command (assuming current 
working directory being the output folder):
```{r}
data <- read.table("output/tidyData.txt", header = TRUE) 
```
See https://class.coursera.org/getdata-016/forum/thread?thread_id=50 for a 
more thorough description of this output.

### Script operation
The script runs through the following steps:
1. Install dplyr package if missing, and load necessary libraries.

2. If missing, download input dataset. Unzip it, and create output folder.

3. Build a table of the interesting features. In this script, this is interpreted 
as all features from the original dataset containing "mean" or "std" in its name. 

4. Build a table of all the activities from the original dataset.

5. From a part of the dataset (i.e. training or test) as well as the above two 
tables, build a partial "raw" version of the tidy dataset. These two parts 
each contain one column per "interesting" feature, as well as columns describing 
which activity (in human readable form) and subject the measurement stems from.
NOTE: At this point, the dataset is tidy as each column corresponds to a single 
measurement and each row corresponds to a single measurement of these variables.

6. Combine the two parts into a single large raw tidy dataset.

7. Summarize the dataset by calculating the mean of each feature per subject/activity 
pair.

8. Write the output tidy dataset to the output folder.

